work_dir: ./work_dir/smarthome/xview1/agcn_rgb_lstm_joint
model_saved_name: ./runs/smarthome_cv1_agcn_rgb_lstm_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/smarthome/xview1/train_data_joint.npy
  label_path: ./data/smarthome/xview1/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

train_rgb_feeder_args:
  data_path: ./data/smarthome/xview1/train_data_rgb_joint.npy
  label_path: ./data/smarthome/xview1/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/smarthome/xview1/val_data_joint.npy
  label_path: ./data/smarthome/xview1/val_label.pkl

test_rgb_feeder_args:
  data_path: ./data/smarthome/xview1/val_data_rgb_joint.npy
  label_path: ./data/smarthome/xview1/val_label.pkl

# model
model: model.rgb_lstm_agcn.Model
#weights: ./runs/smarthome_cs_agcn_rgb_lstm_joint-2-3.pt
model_args:
  num_class: 31
  num_point: 15
  num_person: 1
  graph: graph.smarthome.Graph
  graph_args:
    labeling_mode: "spatial"

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
# Update based on the nmber f GPU s available
device: [0, 1]
batch_size: 16
test_batch_size: 16
# num_epoch: 60
num_epoch: 60
nesterov: True
